export enum ThemeColors {
  Background = 'background',
  Brand = 'brand',
  Primary = 'primary',
  PrimaryInverted = 'primaryInverted',
  Secondary = 'secondary',
  Accent = 'accent',
  Anchor = 'anchor',
  Error = 'error',
  Info = 'info',
  Success = 'success',
  Warning = 'warning',
  Collection = 'collection',
  Article = 'article',
}
